export interface ServiceTemplate {
  slug: string;
  name: string;
  shortName: string;
  metaTitle: (city: string) => string;
  metaDesc: (city: string) => string;
  heroTitle: (city: string) => string;
  heroDesc: (city: string) => string;
  intro: (city: string, county: string) => string;
  bullets: string[];
  faq: (city: string, distanceFromCeres: string) => { q: string; a: string }[];
  ctaLabel: string;
}

export const serviceTemplates: ServiceTemplate[] = [
  {
    slug: 'adu',
    name: 'ADU Construction',
    shortName: 'ADU',
    metaTitle: (city) => `ADU Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed ADU contractor building detached ADUs, garage conversions & attached ADUs in ${city}, CA. Lic. #1106454. Free estimates: (209) 241-3765.`,
    heroTitle: (city) => `ADU Construction in ${city}, CA`,
    heroDesc: (city) => `Build a permitted, rental-ready accessory dwelling unit in ${city}. C Hernandez Construction handles framing, coordination, and construction from start to finish.`,
    intro: (city, county) => `The demand for ADUs in ${city} has never been higher. California's streamlined ADU laws have made it easier than ever to add a detached unit, convert a garage, or build an attached suite on your ${city} property. C Hernandez Construction is a licensed general contractor (Lic. #1106454) based in nearby Ceres — we've built ADUs across ${county} and know the permit process, setback rules, and inspection requirements in ${city} inside and out. Whether you want to generate rental income or house a family member, we'll get your ADU built right.`,
    bullets: [
      'Detached ADUs — standalone structures up to 1,200 sq ft',
      'Garage conversion ADUs — fastest, most affordable option',
      'Attached ADUs — addition to the main home with separate entry',
      'Junior ADUs (JADU) — interior conversion up to 500 sq ft',
      'Full permit coordination with the local building department',
      'Licensed crew: framing, MEP rough-in, drywall, paint, finish',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you build ADUs in ${city}?`, a: `Yes — ${city} is one of our active service areas. We're based in Ceres (${distanceFromCeres} away) and regularly build ADUs throughout the region. Call (209) 241-3765 for a free site visit.` },
      { q: `How long does an ADU permit take in ${city}?`, a: `California law requires cities to approve complete ADU applications within 60 days. Most cities in the Central Valley process standard applications in 4–8 weeks. We'll help you submit a complete package to minimize delays.` },
      { q: `How much does an ADU cost in ${city}?`, a: `A detached ADU in ${city} typically costs $120,000–$250,000 depending on size, finishes, and site conditions. Garage conversions start around $65,000. We provide free, detailed written estimates after a site visit.` },
      { q: `Can I rent out my ADU in ${city}?`, a: `Yes. ADUs can be rented as long-term rentals under California state law. Short-term rental rules vary by city — check ${city}'s municipal code. A permitted ADU also adds significant resale value to your property.` },
    ],
    ctaLabel: 'Get a Free ADU Estimate →',
  },
  {
    slug: 'framing',
    name: 'Structural Framing',
    shortName: 'Framing',
    metaTitle: (city) => `Framing Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed structural framing contractor in ${city}, CA. Platform framing for new homes, ADUs, and room additions. Lic. #1106454. Call (209) 241-3765.`,
    heroTitle: (city) => `Structural Framing in ${city}, CA`,
    heroDesc: (city) => `Precision platform framing for new homes, ADUs, and additions in ${city}. Licensed, fast, and built to pass inspection the first time.`,
    intro: (city, county) => `Framing is the skeleton of every structure — and getting it right determines everything that follows. C Hernandez Construction specializes in residential platform framing for new homes, ADUs, additions, and second-story projects throughout ${city} and ${county}. We're licensed (Lic. #1106454), experienced in California building codes, and known for clean, accurate work that passes city inspections without corrections. Whether you're a homeowner, GC, or developer, we frame it right the first time.`,
    bullets: [
      'New home platform framing (single and two-story)',
      'ADU and detached structure framing',
      'Room addition and second-story addition framing',
      'Shear walls, headers, and structural elements per engineered plans',
      'Subfloor, wall, and roof framing systems',
      'Work with your architect/engineer plans or refer you to trusted drafters',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you do framing work in ${city}?`, a: `Yes — we frame throughout ${city} and the surrounding Central Valley. We're based in Ceres, ${distanceFromCeres} away, and are on site fast. Call (209) 241-3765.` },
      { q: 'What type of framing do you specialize in?', a: 'We specialize in residential platform framing — the standard method for California homes. This includes new construction, ADU framing, room additions, and second-story additions.' },
      { q: 'Do you work from engineered plans?', a: `Yes. We work from architect or engineer-stamped plans. If you don't have plans yet, we can refer you to trusted local drafters familiar with Central Valley building departments.` },
      { q: 'Can you frame just a part of my project?', a: `Yes — we can be hired as framing subcontractors by GCs, or directly by homeowners as part of a broader project. We're flexible and work within your timeline.` },
    ],
    ctaLabel: 'Get a Framing Quote →',
  },
  {
    slug: 'additions',
    name: 'Room Additions',
    shortName: 'Additions',
    metaTitle: (city) => `Room Addition Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed room addition contractor in ${city}, CA. Bedroom, family room, and second-story additions. Permitted and built to code. Lic. #1106454. (209) 241-3765.`,
    heroTitle: (city) => `Room Additions in ${city}, CA`,
    heroDesc: (city) => `Expand your ${city} home with a permitted room addition. Bedrooms, family rooms, or full second stories — built and framed by a licensed contractor.`,
    intro: (city, county) => `Instead of moving, many ${city} homeowners are choosing to expand. A room addition is one of the best investments you can make in your home — it adds usable square footage, increases resale value, and lets you stay in the neighborhood you love. C Hernandez Construction builds permitted room additions throughout ${city} and ${county}, handling everything from permit coordination to framing, drywall, and finish work. We're licensed (Lic. #1106454) and our work passes city inspections the first time.`,
    bullets: [
      'Master bedroom and bedroom additions',
      'Family room and living area expansions',
      'Second-story additions over existing footprint',
      'Garage conversions to living space',
      'Primary suite additions with private bathroom',
      'Full permit coordination and structural engineering coordination',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you build room additions in ${city}?`, a: `Yes — we regularly build room additions in ${city}. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 for a free site evaluation.` },
      { q: 'Do I need a permit for a room addition?', a: `Yes — any structural addition to your home requires a building permit. We handle the permit application process and work with the city's building department through inspections and final sign-off.` },
      { q: 'How long does a room addition take?', a: 'A typical room addition takes 3–5 months from permit approval to completion, depending on size and complexity. A second-story addition may take longer due to structural requirements.' },
      { q: 'What does a room addition cost in the Central Valley?', a: 'A single-room addition typically runs $80,000–$180,000 depending on size, site conditions, and finish level. We provide free, detailed written estimates after a site visit.' },
    ],
    ctaLabel: 'Get a Free Addition Estimate →',
  },
  {
    slug: 'roofing',
    name: 'Roofing',
    shortName: 'Roofing',
    metaTitle: (city) => `Roofing Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed roofing contractor in ${city}, CA. Re-roofs, shingle installation, and roof repairs. Lic. #1106454. Free estimates: (209) 241-3765.`,
    heroTitle: (city) => `Roofing Services in ${city}, CA`,
    heroDesc: (city) => `Licensed roofing contractor serving ${city}. Full re-roofs, new shingle installation, and storm damage repairs — done right and built to last.`,
    intro: (city, county) => `The Central Valley sun and seasonal storms are tough on roofs. C Hernandez Construction provides residential roofing services throughout ${city} and ${county} — from full tear-off and re-roofs to new shingle installations on ADUs and additions. We're a licensed general contractor (Lic. #1106454) with crews experienced in residential roofing systems. We use quality materials, work efficiently, and clean up completely when we're done.`,
    bullets: [
      'Full tear-off and re-roof (asphalt shingles)',
      'New roof installation on ADUs and additions',
      'Architectural and 3-tab shingle systems',
      'Roof deck repair and replacement',
      'Flashing installation and replacement',
      'Storm damage repair and insurance documentation',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you do roofing in ${city}?`, a: `Yes — we serve ${city} and surrounding areas for roofing work. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 for a free roof evaluation.` },
      { q: 'How do I know if I need a full re-roof or just repairs?', a: `If your roof is over 20 years old, has widespread granule loss, or has multiple leak points, a full re-roof is usually more cost-effective. We'll give you an honest assessment with no pressure.` },
      { q: 'What shingle brand do you use?', a: `We work with several quality shingle manufacturers including Owens Corning, GAF, and CertainTeed. We'll recommend the best option for your budget and climate needs in the Central Valley.` },
      { q: 'Do you handle roofing permits?', a: 'Yes — in most Central Valley cities, re-roofs and significant repairs require a permit. We handle the permit application and coordinate inspections.' },
    ],
    ctaLabel: 'Get a Free Roofing Estimate →',
  },
  {
    slug: 'drywall',
    name: 'Drywall & Painting',
    shortName: 'Drywall',
    metaTitle: (city) => `Drywall Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed drywall contractor in ${city}, CA. Hang, tape, texture, and interior paint for homes, ADUs, and remodels. Lic. #1106454. (209) 241-3765.`,
    heroTitle: (city) => `Drywall & Interior Finishing in ${city}, CA`,
    heroDesc: (city) => `Professional drywall hanging, taping, texturing, and interior paint in ${city}. Licensed finish work for ADUs, remodels, and new construction.`,
    intro: (city, county) => `The finish quality of your walls and ceilings is what people notice most. C Hernandez Construction provides professional drywall and interior finishing services throughout ${city} and ${county} — from rough hang to smooth finish, texture application, and interior paint. We work on ADUs, home remodels, room additions, and new construction. Licensed (Lic. #1106454) and detail-oriented, we deliver smooth, inspection-ready results every time.`,
    bullets: [
      'Drywall hanging (standard, moisture-resistant, fire-rated)',
      'Tape, mud, and finishing to Level 4 or Level 5',
      'Texture application: smooth, orange peel, knockdown, skip trowel',
      'Interior paint — walls, ceilings, and trim',
      'Patch and repair for existing drywall damage',
      'Drywall for ADUs, additions, remodels, and new homes',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you do drywall work in ${city}?`, a: `Yes — we handle drywall and interior finishing throughout ${city}. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 for a free quote.` },
      { q: 'What texture options do you offer?', a: 'We apply smooth finish, orange peel, knockdown, and skip trowel textures. We can match your existing texture for additions and repairs, or apply a new texture for a remodel.' },
      { q: 'Do you also do paint?', a: `Yes — we offer interior paint as part of our drywall package. We handle primer and finish coats for walls, ceilings, and trim, using quality latex paint appropriate for California's climate.` },
      { q: 'Can you do drywall on an ADU?', a: `Yes — drywall on an ADU is one of our most common jobs. We work through the entire project from frame to paint, or can come in just for the drywall phase if you're managing multiple subs.` },
    ],
    ctaLabel: 'Get a Drywall Quote →',
  },
  {
    slug: 'general-contractor',
    name: 'General Contracting',
    shortName: 'GC Services',
    metaTitle: (city) => `General Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed General Contractor (Lic. #1106454) in ${city}, CA. Full project management for ADUs, additions, remodels, and new homes. Call (209) 241-3765.`,
    heroTitle: (city) => `Licensed General Contractor in ${city}, CA`,
    heroDesc: (city) => `Full-service general contracting in ${city}. C Hernandez Construction manages permits, crews, and construction from start to finish — one point of contact for your entire project.`,
    intro: (city, county) => `Managing a construction project involves permits, schedules, subcontractors, inspections, and constant decision-making. C Hernandez Construction acts as your licensed general contractor (Lic. #1106454) throughout ${city} and ${county}, handling every step from initial permit submission to final walk-through. We coordinate our own crews and trusted subcontractors, keep you updated throughout, and deliver on time and on budget. One call. One contractor. One completed project.`,
    bullets: [
      'Full project management for ADUs, additions, and remodels',
      'Permit applications and coordination with building department',
      'Schedule and subcontractor coordination (electrical, plumbing, HVAC)',
      'Framing, drywall, roofing, and finish work with our own crews',
      'Regular client updates and transparent cost tracking',
      'Final inspection coordination and certificate of occupancy',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Are you licensed as a General Contractor in ${city}?`, a: `Yes — C Hernandez Construction holds California General Contractor License #1106454, which is valid throughout the state including ${city}. We're fully insured and bonded.` },
      { q: 'What size projects do you manage?', a: `We manage projects from ADU construction ($120K–$250K) to full new home builds and multi-unit residential. We're experienced with Stanislaus and San Joaquin County building departments.` },
      { q: 'Do you handle all permits?', a: `Yes — we submit permits, respond to plan check corrections, schedule inspections, and see the project through to final approval from the ${city} building department.` },
      { q: 'How do I get a quote?', a: `Call (209) 241-3765 or fill out our contact form. We'll schedule a free site visit, review your plans or goals, and provide a detailed written estimate within 24 hours.` },
    ],
    ctaLabel: 'Talk to a General Contractor →',
  },
  {
    slug: 'remodeling',
    name: 'Home Remodeling',
    shortName: 'Remodeling',
    metaTitle: (city) => `Home Remodeling Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed home remodeling contractor in ${city}, CA. Kitchen, bathroom, and whole-home remodels. Lic. #1106454. Free estimates: (209) 241-3765.`,
    heroTitle: (city) => `Home Remodeling in ${city}, CA`,
    heroDesc: (city) => `Transform your ${city} home with a licensed remodeling contractor. Kitchen renovations, bathroom remodels, open-concept conversions, and whole-home updates — done right.`,
    intro: (city, county) => `Home remodeling is one of the most personal construction projects — you're not just building; you're improving your daily life. C Hernandez Construction provides licensed residential remodeling services throughout ${city} and ${county}. We handle kitchen renovations, bathroom remodels, open-concept conversions, laundry room build-outs, and whole-home updates. We're licensed (Lic. #1106454), experienced in ${city}'s permit requirements, and committed to delivering quality finishes on schedule.`,
    bullets: [
      'Kitchen remodels (layout changes, cabinets, countertops, tile)',
      'Bathroom remodels (tile, fixtures, vanity, shower/tub)',
      'Open-concept conversions (load-bearing wall removal)',
      'Laundry room and utility room build-outs',
      'Flooring installation and replacement',
      'Interior paint, trim, and finish carpentry throughout',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you remodel homes in ${city}?`, a: `Yes — we complete remodels throughout ${city} and the Central Valley. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 to schedule a free consultation.` },
      { q: 'Do I need permits for a kitchen or bathroom remodel?', a: `Cosmetic remodels (paint, cabinets, fixtures) typically don't require permits. But layout changes, electrical upgrades, plumbing moves, or removing walls usually do. We'll assess your project and handle permit submissions.` },
      { q: 'Can you remove a load-bearing wall?', a: 'Yes — we have experience with load-bearing wall removal as part of open-concept remodels. This requires engineered plans and a permit, which we coordinate with the city.' },
      { q: 'How long does a kitchen remodel take?', a: 'A typical kitchen remodel takes 4–8 weeks once materials are on site. Timeline depends on scope — a full layout change with new plumbing takes longer than a cabinet and countertop refresh.' },
    ],
    ctaLabel: 'Get a Remodeling Estimate →',
  },
  {
    slug: 'carpentry',
    name: 'Carpentry & Trim',
    shortName: 'Carpentry',
    metaTitle: (city) => `Carpentry Contractor in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed carpentry contractor in ${city}, CA. Finish carpentry, crown molding, built-ins, and custom trim work. Lic. #1106454. Call (209) 241-3765.`,
    heroTitle: (city) => `Carpentry & Finish Trim in ${city}, CA`,
    heroDesc: (city) => `Finish carpentry and custom trim work in ${city}. Crown molding, built-in shelving, door casing, and custom millwork — installed clean and precise.`,
    intro: (city, county) => `The details matter. Finish carpentry is what separates a house from a home — and C Hernandez Construction delivers that level of craft throughout ${city} and ${county}. We install crown molding, base molding, door and window casing, built-in shelving, custom closets, and wainscoting. Our carpenters are precision-focused and experienced working with both new construction and existing homes where older trim profiles need to be matched exactly.`,
    bullets: [
      'Crown molding and coffered ceilings',
      'Base molding and door/window casing',
      'Built-in shelving, entertainment centers, and bookcases',
      'Custom closet systems and built-in wardrobes',
      'Wainscoting and board-and-batten wall treatments',
      'Stair railings, balusters, and newel posts',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you do carpentry work in ${city}?`, a: `Yes — we provide finish carpentry and trim work throughout ${city}. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 for a free quote.` },
      { q: 'Can you match existing trim in my home?', a: 'Yes — matching existing profiles is a regular request. We source matching molding profiles or have custom pieces milled when needed. This is common for additions or partial remodels.' },
      { q: 'Do you build custom built-ins?', a: 'Yes — we design and build custom built-in shelving, entertainment units, and closet systems. We work from your dimensions and preferences to deliver built-ins that fit your space perfectly.' },
      { q: 'Do I need a permit for finish carpentry?', a: 'Generally, finish carpentry work (trim, built-ins, molding) does not require a permit. Structural carpentry work — like modifying framing or load-bearing elements — does.' },
    ],
    ctaLabel: 'Get a Carpentry Quote →',
  },
  {
    slug: 'new-construction',
    name: 'New Construction',
    shortName: 'New Homes',
    metaTitle: (city) => `New Home Construction in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed new home construction contractor in ${city}, CA. Custom single-family homes and residential builds. Lic. #1106454. Free estimates: (209) 241-3765.`,
    heroTitle: (city) => `New Home Construction in ${city}, CA`,
    heroDesc: (city) => `Build your custom home in ${city} with a licensed general contractor. C Hernandez Construction manages new residential construction from permits to final walk-through.`,
    intro: (city, county) => `Building a new home in ${city} is a major undertaking — and you need a licensed contractor you can trust from day one. C Hernandez Construction manages new residential construction projects throughout ${city} and ${county}, handling permit coordination, foundation and framing, trade subcontractor management, and finish work. We're licensed (Lic. #1106454), experienced with ${county}'s building departments, and committed to delivering your new home on time and on budget.`,
    bullets: [
      'Full new home construction management (GC services)',
      'Permit submission and plan check coordination',
      'Foundation, framing, and structural systems',
      'Trade coordination: electrical, plumbing, HVAC subcontractors',
      'Exterior finishes: roofing, siding, windows, doors',
      'Interior finishes: drywall, paint, flooring, trim, and fixtures',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you build new homes in ${city}?`, a: `Yes — we build new single-family homes in ${city} and across the Central Valley. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 to discuss your project.` },
      { q: 'Do I need to have plans before calling you?', a: `No — you can contact us at any stage. We can refer you to trusted architects and engineers, or work from plans you already have. We'll walk you through the entire process.` },
      { q: 'How long does it take to build a new home?', a: 'A typical single-family home takes 8–14 months from permit approval to occupancy, depending on size, finishes, and site conditions. We provide a detailed timeline in our proposal.' },
      { q: 'Do you handle the permit process for new construction?', a: `Yes — new construction permits in ${city} involve multiple agencies and plan check rounds. We manage the entire permit process, from application to final inspection and certificate of occupancy.` },
    ],
    ctaLabel: 'Discuss Your New Home Build →',
  },
  {
    slug: 'doors-windows',
    name: 'Doors & Windows',
    shortName: 'Doors & Windows',
    metaTitle: (city) => `Door & Window Installation in ${city}, CA | C Hernandez Construction`,
    metaDesc: (city) => `Licensed door and window installation contractor in ${city}, CA. Interior, exterior, and patio doors. Sliding and casement windows. Lic. #1106454. (209) 241-3765.`,
    heroTitle: (city) => `Door & Window Installation in ${city}, CA`,
    heroDesc: (city) => `Professional door and window installation in ${city}. Exterior entry doors, interior doors, patio doors, and window replacement — installed properly and sealed tight.`,
    intro: (city, county) => `Properly installed doors and windows make a significant difference in your home's energy efficiency, security, and appearance. C Hernandez Construction provides door and window installation services throughout ${city} and ${county} — from new exterior entry doors and interior passage doors to patio sliders and window replacements. We're a licensed contractor (Lic. #1106454) and ensure every installation is properly flashed, insulated, and finished for the Central Valley's climate.`,
    bullets: [
      'Exterior entry door installation and replacement',
      'Interior door installation (passage, closet, pocket)',
      'Patio sliding doors and French door installation',
      'Window replacement (single, double, casement, sliding)',
      'Proper flashing, wrapping, and waterproofing on all exterior openings',
      'Trim and casing finish work included',
    ],
    faq: (city, distanceFromCeres) => [
      { q: `Do you install doors and windows in ${city}?`, a: `Yes — we serve ${city} for door and window installation. We're based in Ceres, ${distanceFromCeres} away. Call (209) 241-3765 for a free quote.` },
      { q: 'Do I need a permit to replace a window or door?', a: `Like-for-like window and door replacements (same size opening) typically don't require a permit in most California cities. Enlarging openings or adding new openings in structural walls does require a permit.` },
      { q: 'Can you install any brand of door or window?', a: 'Yes — we work with whatever you supply, or we can source and supply doors and windows at competitive prices. We work with Milgard, Andersen, JELD-WEN, and other quality brands.' },
      { q: 'Do you do the trim and casing after installation?', a: 'Yes — we include trim and casing as part of our installation service. Every door and window gets properly cased inside and properly flashed and trimmed outside.' },
    ],
    ctaLabel: 'Get a Door & Window Quote →',
  },
];

export const SERVICE_SLUGS = serviceTemplates.map(s => s.slug);

export function getServiceTemplate(slug: string): ServiceTemplate | undefined {
  return serviceTemplates.find(s => s.slug === slug);
}
